### ISSUE TITLE
Trader features

### ISSUE THREAD

**Issue by Dandielo** [Dandielo/dtlTraders#1]
What features you lack, what would you like to have added?

Features list:

**Comment by ravenfallls** [comment]
only one feature, multi currencies.
ive run ecco plugins that can handle multi currencies but im yet to see a shop that can do this.
could be handy to be able to by stuff in cash or special items in tokens earned through daily tasks.

**Comment by Dandielo** [comment]
This is already there, to be honest. I've added this along with paying for items with: health, experience, food level and levels also a really basic way of bartering (item for item) I'm just not able to work on this to much anymore, sorry :/ It needs a lot of bug fixes in this current state but I'm not able to do this with my lack of time. sorry.
