### ISSUE TITLE
cant sell items

### ISSUE THREAD

**Issue by krause3284** [Dandielo/dtlTraders#36]
Im trying to use your latest version. But whenever I have an item in my hand or inventory thats setup in the config to alter costs, it disappears. Also any item I put in buy stock, if i have on hand or inventory also disappears as soon as I click on the NPC

**Comment by TheMaddog** [comment]
Same problem here, plugin seems dead. Recommend finding another plugin.

**Comment by writeescape** [comment]
can you get me the error log of what happens when you have something in your inventory that the shop sells. and i will take a look at the code
