### ISSUE TITLE
Items not showing in dtlTrader inventory

### ISSUE THREAD

**Issue by BLAKOUT13** [Dandielo/dtlTraders#52]
I am running a cauldron server 1.7.10 and i have the right citizens plugin (the one meant for cauldron) and i added the dtlTraders plugin. When ever i try to put items in his inventory i press unlock stock and then i add the items. I click exit and save and it brings me back to the regular screen and the items are not there. If i click the square where i added the items into, it says buying <that item> . so it gives me the items but they are invisible in his inventory so i cant see what i am buying or selling. If you could help i would be very happy.
Thanks - BLAKOUT13

**Comment by Dandielo** [comment]
It's probably an issue with a the few latest builds, and tbh I'm right now working on a quite huge update for this plugin, separating it into two smaller ones. I will 100% check the new code for this issue but right now I cannot really fix it within the old code.

Anyway thanks for the bug report, I'm adding it to my test list.

**Comment by BLAKOUT13** [comment]
So i know this has been a while but any luck dude?

**Comment by Pulverizer** [comment]
@Dandielo Please can you fix this. Servers using plugins and mods together are still stuck on 1.7.10.
Would be really helpful.
