### ISSUE TITLE
I can't download the latest version.

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Dandielo/dtlTraders#53]
Hellow owner im still dtlTrader 3.4.0-beta but i download the **R: 3.4.2 (1.8/1.8.8) for 1.8.1 Mar 03, 2016** and put the dtlTrader for 1.8.8 not 1.8 i need the 3.4.2
Look
![2016-03-26_17 09 17](https://cloud.githubusercontent.com/assets/13610530/14059211/0c7b23a2-f2ce-11e5-9c7f-f26973a597b7.png)

**Comment by Dandielo** [comment]
This is only a issue with the command, the version is 3.4.2 just the command shows the invalid value, going to update that one too, sorry for the misleading message
