### ISSUE TITLE
Price gone after changing location.

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Dandielo/dtlTraders#54]
Hellow @Dandielo The price i set will gone after i change in to other location the item
I download the **R: 3.4.2 (1.8/1.8.8) for 1.8.1 Mar 03, 2016** but i'm still in 3.4.0-beta help me :disappointed:

**Comment by Dandielo** [comment]
This is an issue, I will check whats goin on with this one, can you tell me what item did you changed (like normal stone etc? or potions and so on?)

**Comment by PinoyLifeCraft** [comment]
Splash Potion and bow D-helmet,armor,leg,boots and i don't know if the other items will be like this :negative_squared_cross_mark:
