### ISSUE TITLE
Splash Potion 3.4.0

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Dandielo/dtlTraders#55]
Hellow @Dandielo the location of Splash Potion will change to vacant space if will arrange it after i stop and start my server it will change to vacant space :cry:

**Comment by Dandielo** [comment]
There was an information that Splash Potions will have issues with 3.4.2 and higher, because the way they are serialized and vice versa changed a lot because of the API changes in bukkit

**Comment by PinoyLifeCraft** [comment]
So it's a Bukkit bug?
But it will go to other location even i put them in a place that i want?

**Comment by Dandielo** [comment]
Ok It's not a bukkit bug, but it's a issue because of using the new dtlTraders version, however can you tell me the following things?

Spigot/Bukkit version: ?
dtlCore version: ?
dtlTraders version: ?

**Comment by PinoyLifeCraft** [comment]
Spigot version : git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
dtlCore version : R: 3.4.2 (1.8/1.8.8) for 1.8.1 Mar 03, 2016
dtlTraders version : R: 3.4.2 (1.8/1.8.8) for 1.8.1 Mar 03, 2016 **1.8.8**
